Map<String, String> ar = {
  'app_name': 'Crazy Food',
  'general_error': 'حدث خطآ ما',
  'no_internet':'لا يوجد اتصال بالانترنت',
  'home_tab': 'الرئيسية',
  'favourite_tab': 'المفضلة',
  'notification_tab': 'الاشعارات',
  'settings_tab': 'الاعدادت',
  'categories': 'أقسام التطبيق',
  'popular':'العروض الشائعه',
  'name': 'الاسم',
  'email': 'البريد الالكتروني',
  'birth_date': 'تاريخ الميلاد',
  'password': 'كلمه المرور',
  'sign_in': 'تسجيل الدخول',
  'sign_up': 'انشاء حساب',
  'login': 'تسجيل الدخول',
  'register': 'تسجيل حساب',
  'signup_msg':'للاستمرارانشئ حساب باستخدام الايميل واكلمه المرور',
  'name_hint':'ادخل الاسم',
  'code_hint':'الرمز',
  'user_name_hint':'اسم المستخدم',
  'email_hint':'ادخل البريد الالكتروني',
  'password_hint':'ادخل كلمه المرور',
  'empty': 'حقل فارغ',
  'phone': 'رقم الهاتف',
  'login_success': 'تم التسجيل بنجاح',
  'register_success': 'تم التسجيل بنجاح',
  'forget_password': 'نسيت كلمه المرور؟',
  'male': 'ذكر',
  'female': 'أنثي',
  'reset_password': 'استعاده كلمه المرور',
  'reset_password_desc': 'من فضلك ادخل البريد الالكتروني لاستعاده كلمه المرور',
  'level': 'مستوي',
  'next': 'التالي',
  'order_message':'اطلب اي منتج للحصول علي الخصم',
  'order_now':'اطلب الان --->',
  'order':'الطلب',
  'reviews':'التقييمات',
  'details':'التفاصيل',
  'location_map':'خريطة المكان',
  'shipping_details':'تفاصيل التسوق',
  'orders_details':'تفاصيل الطلب',
  'description':'الوصف',
  'your_order_placed':'Your Order was placed for delivery',
  'your_order_pending':'Your Order is pending for confirmation will confirmed whithin 5 minutes.',
  'your_order_confirmed':'Your Order is confirmed will deliver soon  whithin 5 minutes.',
  'your_order_processing':'Your Order is processing to deliver you on time.',
  'your_order_delivered':'Product deliver to you and marked as delivered by customer.',
  'delete_cart_item':'هل تريد حذف هذا العنصر من السلة؟',
  'checkout':'',
  'delete':'حذف',
  'cancel':'الغاء',
  'similar_products': 'المنتجات المشابهه',
  'no_cat_found':'لاتوجد أقسام',
  'all_orders':'كل الطلبات',
'processing':'جاري المعالجة',
'pending':'ف الانتظار',
'delivery':'تم التوصيل',
  'order_placed_dts':'طلب رقم #12364 مقيد من اجل التوصيل',
  'pending_dts':'طلبك في انتظار الارسال',
  'confirmed_dts':'طلبك تم التاكيد من اجل الارسال',
  'processing_dts':'طلبك ف المعالجه',
  'delivered_dts':'طلبك تم الاستلام',
  'order_placed':'تم الطلب',
  'confirmed':'تم التاكيد',
  'delivered':'تم التوصيل',
  'pay':'دفع',
  'add_new_payment':'اضافه وسيله دفع جديده',
  'order_success':'تم الطلب بنجاح',
  'track_my_order':'تاكيد الطلب',
  'go_back':'رجوع',
  'order_success_data':' رقمك طلب #123456  تم الارسال بنجاح!',
  'selected_location':'العنوان المختار:',
  'current_location':'العنوان الحالي:',
  'add_address':'اضافه العنوان',
  'cart_empty':'!السلة فارغة',
  'create_order_sucess':'تم ارسال الطلب بنجاح',
  'order_message':'اطلب ماتحتاجه من التطبيق واحصل علي الخصم',
  'change_password':'تغيير كلمة المرور',
  'change_lang':'تغيير اللغة',
  'change_color':'تغيير اللون',
  'account_info':'البيانات الشخصية',
  'old_password':'كلمة المرور القديمة',
  'new_password':'كلمة المرور الجديدة',
  'confirm_password':'تاكيد كلمة المرور',
  'change_password_success':'تم تغيير كلمه المرور بنجاح',
  'change_profile_success':'تم تعديل بيانات الحساب بنجاح',
  'update_profile':'تعديل البيانات',
  'cart':'السلة',
  'see_all':'عرض الكل',
  'discount':'خصم',
  'home':'الرئيسية',
  'offers_tab':'العروض',
  'orders_tab':'الطلبات',
  'more_tab':'المزيد',
  'quantity':'الكمية',
  'calories':'سعرات حرارية',
  'search':'بحث',
  'total':'الاجمالي :',
  'checkout_bar':'الدفع والعنوان',
  'add_new':'اضافة جديد',
  'shipping_details':'تفاصيل الطلب',
  'paid':'المدفوع',
  'login':'تسجيل الدخول',
  'register':'انشاء حساب',
  'sign_out':'تسجيل الخروج',
  'user_hint':'الاسم',
  'phone_hint':'رقم الجوال',
  'gender':'النوع:',
  'male':'ذكر',
  'female':'انثي',
  'hearing_impairment':'ذوي الاعاقة السمعيه',
  'user':'المستخدم',
  'conver':'تحويل',
  'from_hint':'الي :',
  'to_hint':'من :',
  'subject':'الموضوع :',
  'cancel':'الغاء',
  'send':'ارسال',
  'qodra':'قدرة',
  'contact_us':'تواصل معنا!',
  'color':'اللون',
  'language':'اللغة',
  'check_email':'تم ارسال رساله على الايميل الخاص بك',
  'write_here':'اكتب هنا',
  'convert':'تحويل',
  'empty':'فارغ',
  'choose_image':'اختر مصدر الصورة',
  'gallery':'معرض الصور',
  'camera':'الكاميرا'
};