Map<String, String> en = {
  'app_name': 'Crazy Food',
  'general_error': 'Some Thing Went Wrong',
  'no_internet':'No internet connection',
  'home_tab': 'Home',
  'favourite_tab': 'Favourites',
  'notification_tab': 'Notifications',
  'settings_tab': 'Settings',
  'categories': 'Categories',
  'name': 'Name',
  'email': 'Email',
  'code_hint':'enter password',
  'birth_date': 'BirthDate',
  'password': 'Password',
  'sign_in': 'Sign In',
  'sign_up': 'Sign Up',
  'name_hint':'Enter Full Name',
  'email_hint':'Enter Email',
  'popular':'Popular Deals',
  'password_hint':'Enter Password',
  'signup_msg':'signup with your email and password to continue',
  'empty': 'Empty Field',
  'phone': 'Phone',
  'login_success': 'Login Success',
  'register_success': 'Register Success',
  'forget_password': 'forget password?',
  'male': 'Male',
  'female': 'Female',
  'reset_password':'Reset Password',
  'reset_password_desc':'enter your email to reset password',
  'level':'Level',
  'next':'Next',
  'order_message':'Order any food from app to get the discount',
  'order_now':'Order Now -->',
  'order':'Order',
  'reviews':'Reviews',
  'details':'Details',
  'location_map':'Location Map',
  'shipping_details':'Shipping Details',
  'orders_details':'Orders Details',
  'description':'Details',
  'your_order_placed':'Your Order was placed for delivery.',
  'your_order_pending':'Your Order is pending for confirmation will confirmed whithin 5 minutes.',
  'your_order_confirmed':'Your Order is confirmed will deliver soon  whithin 5 minutes.',
  'your_order_processing':'Your Order is processing to deliver you on time.',
  'your_order_delivered':'Product deliver to you and marked as delivered by customer.',
  'checkout':'Checkout  >>',
  'delete_cart_item':'Are you sure remove this item from cart?',
  'delete':'Delete',
  'cancel':'Cancel',
  'similar_products': 'Similar Products',
  'no_cat_found':'No category found',
  'all_orders':'All Orders',
  'processing':'Processing',
  'pending':'Pending',
  'delivery':'Delivery',
  'order_placed':'Order Placed',
  'confirmed':'Confirmed',
  'delivered':'Delivered',
  'order_placed_dts':'your order #132 was placed for delivery.',
  'pending_dts':'your orderis pending for confirmation.',
  'confirmed_dts':'your product is confirmed to deliver',
  'processing_dts':'your product is processing to deliver',
  'delivered_dts':'your product is delivered to you ',
  'pay':'Pay',
  'add_new_payment':'ِAdd new Payment',
  'order_success':'Order Successfull',
  'track_my_order':'Track my order',
  'go_back':'Go back',
  'order_success_data':'your order #123456 is places successfully',
  'selected_location':'Selected Location:',
  'current_location':'Current Location:',
  'add_address':'Add Address',
  'cart_empty':'Cart is empty!!',
  'create_order_sucess':'Order created successfully',
'order_message':'Order any food from app and get the discount',
  'change_password':'Change Password',
  'change_lang':'Change Language',
  'account_info':'Account Information',
  'old_password':'Old password',
  'new_password':'New password',
  'confirm_password':'Confirm password',
  'change_password_success':'Change password successfully',
  'change_profile_success':'Update profile data successfully',
  'update_profile':'Update profile',
'cart':'Cart',
'see_all':'See All ',
'discount':'Discount',
'home':'Home',
'offers_tab':'Offers',
'orders_tab':'Orders',
'more_tab':'More',
'quantity':'Quantity',
'calories':'Caleories',
'search':'Search',
  'total':'Total: ',
  'checkout_bar':'Checkout',
  'add_new':'Add new',
  'paid':'Paid',
  'login':'Login',
  'register':'Register',
  'sign_out':'ٍSignOut',
  'user_hint':'User',
  'user_name_hint':'User Name',
  'phone_hint':'Phone number',
  'gender':'Gender:',
  'male':'Male',

  'female':'Female',
  'register':'Register',
  'sign_out':'ٍSignOut',
  'hearing_impairment':'Hearing Impairment',
  'user':'User',
  'conver':'Convert',
'from_hint':'From :',
'to_hint':'To :',
  'subject':'Subject :',
'cancel':'Cancel',
'send':'Send',
  'qodra':'Qudra',
  'contact_us':'Contact us !!',
'color':'Color',
  'language':'Language',
  'check_email':'Send message to your email',
  'write_here':'Write here..',
  'convert':'Convert',
  'empty':'Empty',
  'choose_image':'Choose image',
  'gallery':'Gallery',
  'camera':'Camera',
  'change_color':'Change Color',
};
